- name: Create Load Balancer Security Group
  ec2_group:
    name: VacationVibe-LoadBalancer-SecurityGroup
    description: Security group for VacationVibe load balancer
    vpc_id: "{{ vpc.id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
    state: present
  register: load_balancer_security_group

- name: Create Load Balancer
  elb_application_lb:
    name: VacationVibe-LoadBalancer
    subnets:
      - "{{ subnet.id }}"
    security_groups:
      - "{{ load_balancer_security_group.group_id }}"
    region: "{{ aws_region }}"
    state: present
  register: load_balancer

- name: Create Target Group
  elb_target_group:
    name: VacationVibe-TargetGroup
    protocol: "HTTP"
    port: 80
    vpc_id: "{{ vpc.id }}"
    region: "{{ aws_region }}"
    health_check_path: "/"
    state: present
  register: target_group

- name: Register Backend Instances with Target Group
  elb_target:
    target_group_arn: "{{ target_group.target_group_arn }}"
    targets:
      - id: "{{ backend_instance.id }}"
        port: 8080
    region: "{{ aws_region }}"
    state: present
  register: target

- name: Create Listener for Load Balancer
  elb_application_lb_listener:
    load_balancer_arn: "{{ load_balancer.load_balancer_arn }}"
    protocol: "HTTP"
    port: 80
    default_actions:
      - type: forward
        target_group_arn: "{{ target_group.target_group_arn }}"
    region: "{{ aws_region }}"
    state: present
