- name: Load Terraform Output
  hosts: all
  gather_facts: false
  tasks:
    - name: Retrieve Terraform Output
      command:
        cmd: "terraform output -json -state=/path/to/terraform.tfstate"
      register: tf_output

    - name: Print Output Variables
      debug:
        var: tf_output.stdout | from_json
